<!--
 * @Author: liming
 * @Date: 2021-08-12 00:51:09
 * @LastEditTime: 2021-08-12 00:52:17
 * @FilePath: \01-Promise★\04-一些文章解析Promise\01-Promise用法小结\代码手敲\05-reject的用法.html
-->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <script>
        // 函数定义
      function promiseClick() {
        let p = new Promise(function (resolve, reject) {
          setTimeout(function () {
            var num = Math.ceil(Math.random() * 20); //生成1-10的随机数
            console.log("随机数生成的值：", num);
            if (num <= 10) {
              resolve(num);
            } else {
              reject("数字太于10了即将执行失败回调");
            }
          }, 2000);
        });
        return p;
      }

    //   函数调用
      promiseClick().then(
        function (data) {
          console.log("resolved成功回调");
          console.log("成功回调接受的值：", data);
        },
        function (reason) {
          console.log("rejected失败回调");
          console.log("失败执行回调抛出失败原因：", reason);
        }
      );
    </script>
  </body>
</html>
